/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomeScreen.java
 *
 * Created on Jun 8, 2010, 1:39:53 PM
 */

package UI;

import java.util.*;

/**
 *
 * @author HANG Feifei
 */
public class HomeScreen extends javax.swing.JFrame {
    private static final int TABLES_PANEL = 0;
    private static final int QUERIES_PANEL = 1;
    private static final int VIEWS_PANEL = 2;

    private String dbContainer = null;
    private String current_database = null;
    private UI.Panel.Panel_Template current_panel = null;

    private BSQL.Server_Java server = null; // Basement Server

    /** Creates new form HomeScreen */
    public HomeScreen( String LookAndFeel, String DBContainer, int port, boolean offline ) {
        this.current_database = DBContainer;
        this.server = new BSQL.Server_Java( this, this.current_database, port ); // initialize the daemon thread for server

        this.setDefaultCloseOperation( javax.swing.JFrame.EXIT_ON_CLOSE );
        UI.Theme.Themes.setLookAndFeel( LookAndFeel );
        initComponents();
        this.dbContainer = DBContainer;
        this.initialDatabase( this.dbContainer );
        this.switchContentPanel( TABLES_PANEL );
        
        String portNumber = "Offline";
        if( !offline ) {
            portNumber = String.valueOf( port );
            this.server.setCurrentPanel( this.current_panel );
            this.server.setDaemon( true );
            this.server.start();
        }
        this.setTitle( this.dbContainer + ":" + portNumber + " - Basement" );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        Panel_Database = new javax.swing.JPanel();
        Button_Tables = new javax.swing.JButton();
        Button_Queries = new javax.swing.JButton();
        Button_Views = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ComboBox_Database = new javax.swing.JComboBox();
        Button_Database_Create = new javax.swing.JButton();
        Button_Database_Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Panel_Task_Container = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        Button_Toolbar_Database_Create = new javax.swing.JButton();
        Button_Toolbar_Close = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Button_Toolbar_Database_Delete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_Database_New = new javax.swing.JMenuItem();
        MenuItem_Database_Delete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItem_Close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItem_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basement");

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(220);

        Panel_Database.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Database.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(158, 169, 191)));

        Button_Tables.setText("Tables");
        Button_Tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TablesActionPerformed(evt);
            }
        });

        Button_Queries.setText("Queries");
        Button_Queries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_QueriesActionPerformed(evt);
            }
        });

        Button_Views.setText("Views");
        Button_Views.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ViewsActionPerformed(evt);
            }
        });

        jLabel2.setText("Current Database:");

        ComboBox_Database.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_DatabaseItemStateChanged(evt);
            }
        });

        Button_Database_Create.setText("Create a Database...");
        Button_Database_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Database_CreateActionPerformed(evt);
            }
        });

        Button_Database_Delete.setText("Delete Current Database...");
        Button_Database_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Database_DeleteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(158, 169, 191));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("  Database");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout Panel_DatabaseLayout = new javax.swing.GroupLayout(Panel_Database);
        Panel_Database.setLayout(Panel_DatabaseLayout);
        Panel_DatabaseLayout.setHorizontalGroup(
            Panel_DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addGroup(Panel_DatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Tables, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Button_Queries, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Button_Views, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox_Database, 0, 194, Short.MAX_VALUE)
                    .addComponent(Button_Database_Create, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Button_Database_Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_DatabaseLayout.setVerticalGroup(
            Panel_DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DatabaseLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Tables, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Queries, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Views, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_Database, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Database_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Database_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(Panel_Database);

        Panel_Task_Container.setBackground(new java.awt.Color(130, 144, 199));

        javax.swing.GroupLayout Panel_Task_ContainerLayout = new javax.swing.GroupLayout(Panel_Task_Container);
        Panel_Task_Container.setLayout(Panel_Task_ContainerLayout);
        Panel_Task_ContainerLayout.setHorizontalGroup(
            Panel_Task_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        Panel_Task_ContainerLayout.setVerticalGroup(
            Panel_Task_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(Panel_Task_Container);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel3.setText(" BSQL database engine ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.add(jLabel3);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Button_Toolbar_Database_Create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Database.png"))); // NOI18N
        Button_Toolbar_Database_Create.setToolTipText("New");
        Button_Toolbar_Database_Create.setFocusable(false);
        Button_Toolbar_Database_Create.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Toolbar_Database_Create.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_Toolbar_Database_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Toolbar_Database_CreateActionPerformed(evt);
            }
        });
        jToolBar2.add(Button_Toolbar_Database_Create);

        Button_Toolbar_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Stop sign.png"))); // NOI18N
        Button_Toolbar_Close.setToolTipText("Close");
        Button_Toolbar_Close.setFocusable(false);
        Button_Toolbar_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Toolbar_Close.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_Toolbar_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Toolbar_CloseActionPerformed(evt);
            }
        });
        jToolBar2.add(Button_Toolbar_Close);
        jToolBar2.add(jSeparator3);

        Button_Toolbar_Database_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Erase.png"))); // NOI18N
        Button_Toolbar_Database_Delete.setToolTipText("Delete Database...");
        Button_Toolbar_Database_Delete.setFocusable(false);
        Button_Toolbar_Database_Delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Toolbar_Database_Delete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_Toolbar_Database_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Toolbar_Database_DeleteActionPerformed(evt);
            }
        });
        jToolBar2.add(Button_Toolbar_Database_Delete);

        jMenu1.setText("File");

        MenuItem_Database_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem_Database_New.setText("New Database...");
        MenuItem_Database_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Database_NewActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Database_New);

        MenuItem_Database_Delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItem_Database_Delete.setText("Delete Database...");
        MenuItem_Database_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Database_DeleteActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Database_Delete);
        jMenu1.add(jSeparator1);

        MenuItem_Close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem_Close.setText("Close");
        MenuItem_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_CloseActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Close);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        MenuItem_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItem_About.setText("About");
        MenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AboutActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initialDatabase( String DBContainer ) {
        this.ComboBox_Database.removeAllItems();
        ArrayList list = Ctrl.InitialDatabase.getDatabase( DBContainer );
        for( int index = 0; index != list.size(); ++index ) {
            this.ComboBox_Database.addItem( list.get( index ) );
        }
    }

    private void MenuItem_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_CloseActionPerformed
        UI.WelcomeScreen main = new UI.WelcomeScreen();
        Ctrl.ShowDialog.ShowDialog( main );
        this.dispose();
    }//GEN-LAST:event_MenuItem_CloseActionPerformed

    private void ComboBox_DatabaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_DatabaseItemStateChanged
        try{
            this.current_database = this.dbContainer + "/" + this.ComboBox_Database.getSelectedItem().toString();
            this.current_panel.updateContents( this.current_database );
        }catch( Exception excpt ){
            // handle exception
        }
    }//GEN-LAST:event_ComboBox_DatabaseItemStateChanged

    private void MenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AboutActionPerformed
        UI.Dialog.Dialog_About dialog = new UI.Dialog.Dialog_About();
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_MenuItem_AboutActionPerformed

    private void Button_TablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TablesActionPerformed
        this.switchContentPanel( TABLES_PANEL );
    }//GEN-LAST:event_Button_TablesActionPerformed

    private void Button_QueriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_QueriesActionPerformed
        this.switchContentPanel( QUERIES_PANEL );
    }//GEN-LAST:event_Button_QueriesActionPerformed

    private void Button_ViewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ViewsActionPerformed
        this.switchContentPanel( VIEWS_PANEL );
    }//GEN-LAST:event_Button_ViewsActionPerformed

    private void Button_Database_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Database_CreateActionPerformed
        UI.Dialog.Dialog_CreateDatabase dialog = new UI.Dialog.Dialog_CreateDatabase( this, this.dbContainer );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_Button_Database_CreateActionPerformed

    private void Button_Database_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Database_DeleteActionPerformed
        UI.Dialog.Dialog_DeleteDatabase dialog = new UI.Dialog.Dialog_DeleteDatabase( this, this.dbContainer,
                this.ComboBox_Database.getSelectedItem().toString() );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_Button_Database_DeleteActionPerformed

    private void Button_Toolbar_Database_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Toolbar_Database_CreateActionPerformed
        UI.Dialog.Dialog_CreateDatabase dialog = new UI.Dialog.Dialog_CreateDatabase( this, this.dbContainer );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_Button_Toolbar_Database_CreateActionPerformed

    private void MenuItem_Database_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Database_NewActionPerformed
        UI.Dialog.Dialog_CreateDatabase dialog = new UI.Dialog.Dialog_CreateDatabase( this, this.dbContainer );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_MenuItem_Database_NewActionPerformed

    private void MenuItem_Database_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Database_DeleteActionPerformed
        UI.Dialog.Dialog_DeleteDatabase dialog = new UI.Dialog.Dialog_DeleteDatabase( this, this.dbContainer,
                this.ComboBox_Database.getSelectedItem().toString() );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_MenuItem_Database_DeleteActionPerformed

    private void Button_Toolbar_Database_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Toolbar_Database_DeleteActionPerformed
        UI.Dialog.Dialog_DeleteDatabase dialog = new UI.Dialog.Dialog_DeleteDatabase( this, this.dbContainer,
                this.ComboBox_Database.getSelectedItem().toString() );
        Ctrl.ShowDialog.ShowDialog( dialog );
    }//GEN-LAST:event_Button_Toolbar_Database_DeleteActionPerformed

    private void Button_Toolbar_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Toolbar_CloseActionPerformed
        UI.WelcomeScreen main = new UI.WelcomeScreen();
        Ctrl.ShowDialog.ShowDialog( main );
        this.dispose();
    }//GEN-LAST:event_Button_Toolbar_CloseActionPerformed

    private void switchContentPanel( int index ) {
        UI.Panel.Panel_Template taskPanel = null;
        switch (index) {
            case 0:
                taskPanel = new UI.Panel.Tables_Home_Panel( this.current_database );
                break;

            case 1:
                taskPanel = new UI.Panel.Queries_Home_Panel( this.current_database );
                break;

            case 2:
                taskPanel = new UI.Panel.Views_Home_Panel( this.current_database );
                break;

            default:
                break;
        }
        taskPanel.setVisible( true );
        this.jSplitPane1.setRightComponent( taskPanel );
        this.current_panel = taskPanel;
        this.server.setCurrentPanel( this.current_panel );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Database_Create;
    private javax.swing.JButton Button_Database_Delete;
    private javax.swing.JButton Button_Queries;
    private javax.swing.JButton Button_Tables;
    private javax.swing.JButton Button_Toolbar_Close;
    private javax.swing.JButton Button_Toolbar_Database_Create;
    private javax.swing.JButton Button_Toolbar_Database_Delete;
    private javax.swing.JButton Button_Views;
    private javax.swing.JComboBox ComboBox_Database;
    private javax.swing.JMenuItem MenuItem_About;
    private javax.swing.JMenuItem MenuItem_Close;
    private javax.swing.JMenuItem MenuItem_Database_Delete;
    private javax.swing.JMenuItem MenuItem_Database_New;
    private javax.swing.JPanel Panel_Database;
    private javax.swing.JPanel Panel_Task_Container;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

}
